### ISSUE TITLE
Bootstrap output

### ISSUE THREAD

**Issue by Keats** [kaj/rsass#115]
Bootstrap now compiles without errors (🎊 ) but it produces some invalid CSS as it seems it didn't process everything.

The following bits are present in rsass output:

```
@extend h1;
@extend h2;
@extend h3;
@extend h4;
@extend h5;
@extend h6;
```

```css
@extend .container-fluid;
@media (min-width: 576px) {
  %responsive-container-sm {
    max-width: 540px;
  }
@extend %responsive-container-sm;@extend %responsive-container-sm;}

@extend .container-fluid;
@media (min-width: 768px) {
  %responsive-container-md {
    max-width: 720px;
  }
@extend %responsive-container-md;@extend %responsive-container-md;@extend %responsive-container-md;}

@extend .container-fluid;
@media (min-width: 992px) {
  %responsive-container-lg {
    max-width: 960px;
  }
@extend %responsive-container-lg;@extend %responsive-container-lg;@extend %responsive-container-lg;@extend %responsive-container-lg;}

@extend .container-fluid;
@media (min-width: 1200px) {
  %responsive-container-xl {
    max-width: 1140px;
  }
@extend %responsive-container-xl;@extend %responsive-container-xl;@extend %responsive-container-xl;@extend %responsive-container-xl;@extend %responsive-container-xl;}

@extend .container-fluid;
@media (min-width: 1400px) {
  %responsive-container-xxl {
    max-width: 1320px;
  }
@extend %responsive-container-xxl;@extend %responsive-container-xxl;@extend %responsive-container-xxl;@extend %responsive-container-xxl;@extend %responsive-container-xxl;@extend %responsive-container-xxl;}

```

```
  content: var(--bs-breadcrumb-divider, escape-svg($breadcrumb-divider)) /* rtl: var(--bs-breadcrumb-divider, escape-svg($breadcrumb-divider-flipped)) */;
```

So it looks like some `extend` are not rendered and potentially some variables not replaced?
