### ISSUE TITLE
`map.merge` incorrect output for nested map

### ISSUE THREAD

**Issue by connorskees** [kaj/rsass#116]
For the given input
```scss
@use "sass:map";

$fonts: (
  "Helvetica": (
    "weights": (
      "regular": 400,
      "medium": 500,
      "bold": 700
    )
  )
);

  
a {
    color: inspect(map.merge($fonts, "Helvetica", "weights", "regular", (a: 300)));
}
```

`rsass` will silently remove the keys `medium` and `bold`.

rsass output:
```scss
❯ rsass a.scss
a {
  color: ("Helvetica": ("weights": ("regular": (a: 300))));
}
```
dart-sass output
```scss
❯ dart-sass a.scss
a {
  color: ("Helvetica": ("weights": ("regular": (a: 300), "medium": 500, "bold": 700)));
}
```

```bash
❯ rsass --version
rsass 0.22.2

❯ dart-sass --version
1.35.1
```
