### ISSUE TITLE
Never terminates on this example

### ISSUE THREAD

**Issue by glebm** [kaj/rsass#41]
```scss
@function str-replace($string, $search, $replace: "") {
  $index: str-index($string, $search);

  @if $index {
    @return str-slice($string, 1, $index - 1) + $replace + str-replace(str-slice($string, $index + str-length($search)), $search, $replace);
  }

  @return $string;
}

$x: str-replace(url("a#b#c"), "#", ":");
```

Expected: This should work as `url` is not a function call in CSS.
Actual: Produces no output and never terminates.

It seems to go into the bad arguments branch of `str-slice`, here is the first three  `eprintln!`s:

```
bad str-slice(Call("url", CallArgs([(None, Literal("a#b#c", Double))])), Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true), BinOp(Call("str-index", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, Literal("#", Double))])), false, Minus, false, Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true)))

bad str-slice(Call("url", CallArgs([(None, Literal("a#b#c", Double))])), BinOp(Call("str-index", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, Literal("#", Double))])), false, Plus, false, Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true)), Numeric(Number { value: Ratio { numer: -1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true))

bad str-slice(Call("str-slice", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, BinOp(Call("str-index", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, Literal("#", Double))])), false, Plus, false, Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true)))])), BinOp(Call("str-index", CallArgs([(None, Call("str-slice", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, BinOp(Call("str-index", CallArgs([(None, Call("url", CallArgs([(None, Literal("a#b#c", Double))]))), (None, Literal("#", Double))])), false, Plus, false, Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true)))]))), (None, Literal("#", Double))])), false, Plus, false, Numeric(Number { value: Ratio { numer: 1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true)), Numeric(Number { value: Ratio { numer: -1, denom: 1 }, plus_sign: false, lead_zero: true }, None, true))
```
