### ISSUE TITLE
Selectors can contain newlines

### ISSUE THREAD

**Issue by connorskees** [kaj/rsass#63]
Hello!

Currently `rsass` ignores selectors that are separated by newlines and just uses the last selector:
```scss
a,
b,
c {
  d {
    color: blue;
    e {
      color: orange;
    }
  }
  color: red;
}
```
becomes 
```scss
c {
  color: red;
}
c d {
  color: blue;
}
c d e {
  color: orange;
}
```
and the expected output should be
```scss
a,
b,
c {
  color: red;
}
a d,
b d,
c d {
  color: blue;
}
a d e,
b d e,
c d e {
  color: orange;
}
```

A more reduced example being
```
a,
b {
  color: red;
}
```
which is expected to be emitted unchanged.

**Comment by kaj** [comment]
This bug is also (like #64) triggered by using dos newlines.  Using unix-style newlines in the input, the reduced example gets this output:
```css
a, b {
  color: red;
}
```
... which I think is correct, even if other sass implementations preseve the newlines.

Fixing so input files with dos-style newlines is handled the same as unix-style newlines should hopefully be easy enough to include in the next release of rsass.
