### ISSUE TITLE
Namespaced style values don't have to end in semicolons

### ISSUE THREAD

**Issue by connorskees** [kaj/rsass#64]
Currently this input,
```scss
a {
  color: {
    foo: bar
  }
}
```
results in
```scss
a {
  color-foo: bar\d ;
}
```
but the expected output should be
```scss
a {
  color-foo: bar;
}
```

The output is correct for
```
a {
  color: {
    foo: bar;
  }
}
```
